//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _BWMAP_UPCALL_MANAGER_HH
#define _BWMAP_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "BWMapUpcallInterface.hh"

/** BWMapUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort BWMap and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class BWMapUpcallManager
:	public Smart::IInputHandler<DomainVision::CommVideoImage>
{
private:
	// list of associated updalls
	std::list<BWMapUpcallInterface*> upcalls;

	// call the on_BWMap of all the attached BWMapUpcallInterfaces
	void notify_upcalls(const DomainVision::CommVideoImage &input);
	
protected:
	virtual void handle_input(const DomainVision::CommVideoImage &input) {
		// relay input-handling to all attached BWMapUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	BWMapUpcallManager(
		Smart::InputSubject<DomainVision::CommVideoImage> *subject,
		const int &prescaleFactor=1
	);
	virtual ~BWMapUpcallManager();
	
	void attach(BWMapUpcallInterface *upcall);
	void detach(BWMapUpcallInterface *upcall);
};

#endif
