//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _IMAGEVIEWER_CORE_HH
#define _IMAGEVIEWER_CORE_HH
	
#include "aceSmartSoft.hh"

// include upcall interface
#include "BWMapUpcallInterface.hh"
#include "MapUpcallInterface.hh"

// include communication-objects for output ports

// include all interaction-observer interfaces
#include <ImageViewerObserverInterface.hh>


class ImageViewerCore
:	public SmartACE::ManagedTask
,	public Smart::TaskTriggerSubject
,	public BWMapUpcallInterface
,	public MapUpcallInterface
{
private:
	bool useDefaultState; 
	bool useLogging;
	int taskLoggingId;
	unsigned int currentUpdateCount;
	
	Smart::StatusCode bWMapStatus;
	DGService_DGBasicLink::DGBasicLinkObject bWMapObject;
	Smart::StatusCode mapStatus;
	DGService_DGBasicLink::DGBasicLinkObject mapObject;
	
	
protected:
	virtual int execute_protected_region();
	
	virtual void updateAllCommObjects();
	
	virtual int getPreviousCommObjId();
	
	void triggerLogEntry(const int& idOffset);
	
	
	// overload and implement this method in derived classes to immediately get all incoming updates from BWMap (as soon as they arrive)
	virtual void on_BWMap(const DGService_DGBasicLink::DGBasicLinkObject &input) {
		// no-op
	}
	
	// this method can be safely used from the thread in derived classes
	inline Smart::StatusCode bWMapGetUpdate(DGService_DGBasicLink::DGBasicLinkObject &bWMapObject) const
	{
		// copy local object buffer and return the last status code
		bWMapObject = this->bWMapObject;
		return bWMapStatus;
	}
	// overload and implement this method in derived classes to immediately get all incoming updates from Map (as soon as they arrive)
	virtual void on_Map(const DGService_DGBasicLink::DGBasicLinkObject &input) {
		// no-op
	}
	
	// this method can be safely used from the thread in derived classes
	inline Smart::StatusCode mapGetUpdate(DGService_DGBasicLink::DGBasicLinkObject &mapObject) const
	{
		// copy local object buffer and return the last status code
		mapObject = this->mapObject;
		return mapStatus;
	}
	
	
	
/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<ImageViewerObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(ImageViewerObserverInterface *observer);
	void detach_interaction_observer(ImageViewerObserverInterface *observer);

public:
	ImageViewerCore(Smart::IComponent *comp, const bool &useDefaultState=true);
	virtual ~ImageViewerCore();
	
	inline void setUpLogging(const int &taskNbr, const bool &useLogging=true) {
		this->taskLoggingId = taskNbr;
		this->useLogging = useLogging;
	}
	
	inline bool isLoggingActive() const {
		return useLogging;
	}
	
	inline int getLoggingID() const {
		return taskLoggingId;
	}
	
	inline int getCurrentUpdateCount() const {
		return currentUpdateCount;
	}
	
};
#endif
