//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _MAP_UPCALL_MANAGER_HH
#define _MAP_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "MapUpcallInterface.hh"

/** MapUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort Map and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class MapUpcallManager
:	public Smart::IInputHandler<DomainVision::CommVideoImage>
{
private:
	// list of associated updalls
	std::list<MapUpcallInterface*> upcalls;

	// call the on_Map of all the attached MapUpcallInterfaces
	void notify_upcalls(const DomainVision::CommVideoImage &input);
	
protected:
	virtual void handle_input(const DomainVision::CommVideoImage &input) {
		// relay input-handling to all attached MapUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	MapUpcallManager(
		Smart::InputSubject<DomainVision::CommVideoImage> *subject,
		const int &prescaleFactor=1
	);
	virtual ~MapUpcallManager();
	
	void attach(MapUpcallInterface *upcall);
	void detach(MapUpcallInterface *upcall);
};

#endif
