//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "OneUser.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "OneUserAcePortFactory.hh"


// initialize static singleton pointer to zero
OneUser* OneUser::_oneUser = 0;

// constructor
OneUser::OneUser()
{
	std::cout << "constructor of OneUser\n";
	
	// set all pointer members to NULL
	bWMap = NULL;
	bWMapInputTaskTrigger = NULL;
	bWMapUpcallManager = NULL;
	imageViewer = NULL;
	imageViewerTrigger = NULL;
	map = NULL;
	mapInputTaskTrigger = NULL;
	mapUpcallManager = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "OneUser";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.bWMap.wiringName = "BWMap";
	connections.bWMap.serverName = "unknown";
	connections.bWMap.serviceName = "unknown";
	connections.bWMap.interval = 1;
	connections.bWMap.roboticMiddleware = "ACE_SmartSoft";
	connections.map.wiringName = "Map";
	connections.map.serverName = "unknown";
	connections.map.serviceName = "unknown";
	connections.map.interval = 1;
	connections.map.roboticMiddleware = "ACE_SmartSoft";
	connections.imageViewer.minActFreq = 0.0;
	connections.imageViewer.maxActFreq = 0.0;
	// scheduling default parameters
	connections.imageViewer.scheduler = "DEFAULT";
	connections.imageViewer.priority = -1;
	connections.imageViewer.cpuAffinity = -1;
	
	// initialize members of PlainOpcUaOneUserExtension
	
}

void OneUser::addPortFactory(const std::string &name, OneUserPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void OneUser::addExtension(OneUserExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* OneUser::getComponentImpl()
{
	return dynamic_cast<OneUserAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void OneUser::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode OneUser::connectBWMap(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = bWMap->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->bWMap->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	bWMap->subscribe(connections.bWMap.interval);
	return status;
}
Smart::StatusCode OneUser::connectMap(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = map->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->map->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	map->subscribe(connections.map.interval);
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode OneUser::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectBWMap(connections.bWMap.serverName, connections.bWMap.serviceName);
	if(status != Smart::SMART_OK) return status;
	status = connectMap(connections.map.serverName, connections.map.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void OneUser::startAllTasks() {
	// start task ImageViewer
	if(connections.imageViewer.scheduler != "DEFAULT") {
		ACE_Sched_Params imageViewer_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.imageViewer.scheduler == "FIFO") {
			imageViewer_SchedParams.policy(ACE_SCHED_FIFO);
			imageViewer_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.imageViewer.scheduler == "RR") {
			imageViewer_SchedParams.policy(ACE_SCHED_RR);
			imageViewer_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		imageViewer->start(imageViewer_SchedParams, connections.imageViewer.cpuAffinity);
	} else {
		imageViewer->start();
	}
}

/**
 * Start all timers contained in this component
 */
void OneUser::startAllTimers() {
}


Smart::TaskTriggerSubject* OneUser::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "BWMap") return bWMapInputTaskTrigger;
	if(client == "Map") return mapInputTaskTrigger;
	
	return NULL;
}


void OneUser::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of PlainOpcUaOneUserExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		OneUserPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<OneUserAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition OneUser is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		
		// create client ports
		bWMap = portFactoryRegistry[connections.bWMap.roboticMiddleware]->createBWMap();
		map = portFactoryRegistry[connections.map.roboticMiddleware]->createMap();
		
		// create InputTaskTriggers and UpcallManagers
		bWMapInputTaskTrigger = new Smart::InputTaskTrigger<DomainVision::CommVideoImage>(bWMap);
		bWMapUpcallManager = new BWMapUpcallManager(bWMap);
		mapInputTaskTrigger = new Smart::InputTaskTrigger<DomainVision::CommVideoImage>(map);
		mapUpcallManager = new MapUpcallManager(map);
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.bWMap.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<DomainVision::CommVideoImage>*>(bWMap)->add(wiringSlave, connections.bWMap.wiringName);
		}
		if(connections.map.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<DomainVision::CommVideoImage>*>(map)->add(wiringSlave, connections.map.wiringName);
		}
		
		
		
		// create Task ImageViewer
		imageViewer = new ImageViewer(component);
		// configure input-links
		bWMapUpcallManager->attach(imageViewer);
		mapUpcallManager->attach(imageViewer);
		// configure task-trigger (if task is configurable)
		if(connections.imageViewer.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.imageViewer.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(imageViewer);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				imageViewerTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task ImageViewer" << std::endl;
			}
		} else if(connections.imageViewer.trigger == "DataTriggered") {
			imageViewerTrigger = getInputTaskTriggerFromString(connections.imageViewer.inPortRef);
			if(imageViewerTrigger != NULL) {
				imageViewerTrigger->attach(imageViewer, connections.imageViewer.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.imageViewer.inPortRef << " as activation source for Task ImageViewer" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void OneUser::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void OneUser::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	bWMapUpcallManager->detach(imageViewer);
	mapUpcallManager->detach(imageViewer);
	// unlink the TaskTrigger
	if(imageViewerTrigger != NULL){
		imageViewerTrigger->detach(imageViewer);
		delete imageViewer;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers
	delete bWMapInputTaskTrigger;
	delete bWMapUpcallManager;
	delete mapInputTaskTrigger;
	delete mapUpcallManager;

	// destroy client ports
	delete bWMap;
	delete map;

	// destroy server ports
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of PlainOpcUaOneUserExtension
	
}

void OneUser::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("OneUser.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load OneUser.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: OneUser.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client BWMap
		parameter.getString("BWMap", "serviceName", connections.bWMap.serviceName);
		parameter.getString("BWMap", "serverName", connections.bWMap.serverName);
		parameter.getString("BWMap", "wiringName", connections.bWMap.wiringName);
		parameter.getInteger("BWMap", "interval", connections.bWMap.interval);
		if(parameter.checkIfParameterExists("BWMap", "roboticMiddleware")) {
			parameter.getString("BWMap", "roboticMiddleware", connections.bWMap.roboticMiddleware);
		}
		// load parameters for client Map
		parameter.getString("Map", "serviceName", connections.map.serviceName);
		parameter.getString("Map", "serverName", connections.map.serverName);
		parameter.getString("Map", "wiringName", connections.map.wiringName);
		parameter.getInteger("Map", "interval", connections.map.interval);
		if(parameter.checkIfParameterExists("Map", "roboticMiddleware")) {
			parameter.getString("Map", "roboticMiddleware", connections.map.roboticMiddleware);
		}
		
		
		// load parameters for task ImageViewer
		parameter.getDouble("ImageViewer", "minActFreqHz", connections.imageViewer.minActFreq);
		parameter.getDouble("ImageViewer", "maxActFreqHz", connections.imageViewer.maxActFreq);
		parameter.getString("ImageViewer", "triggerType", connections.imageViewer.trigger);
		if(connections.imageViewer.trigger == "PeriodicTimer") {
			parameter.getDouble("ImageViewer", "periodicActFreqHz", connections.imageViewer.periodicActFreq);
		} else if(connections.imageViewer.trigger == "DataTriggered") {
			parameter.getString("ImageViewer", "inPortRef", connections.imageViewer.inPortRef);
			parameter.getInteger("ImageViewer", "prescale", connections.imageViewer.prescale);
		}
		if(parameter.checkIfParameterExists("ImageViewer", "scheduler")) {
			parameter.getString("ImageViewer", "scheduler", connections.imageViewer.scheduler);
		}
		if(parameter.checkIfParameterExists("ImageViewer", "priority")) {
			parameter.getInteger("ImageViewer", "priority", connections.imageViewer.priority);
		}
		if(parameter.checkIfParameterExists("ImageViewer", "cpuAffinity")) {
			parameter.getInteger("ImageViewer", "cpuAffinity", connections.imageViewer.cpuAffinity);
		}
		
		// load parameters for PlainOpcUaOneUserExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
