//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _GRAYIMAGE1_UPCALL_MANAGER_HH
#define _GRAYIMAGE1_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "GrayImage1UpcallInterface.hh"

/** GrayImage1UpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort GrayImage1 and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class GrayImage1UpcallManager
:	public Smart::IInputHandler<DGService_DGBasicLink::DGBasicLinkObject>
{
private:
	// list of associated updalls
	std::list<GrayImage1UpcallInterface*> upcalls;

	// call the on_GrayImage1 of all the attached GrayImage1UpcallInterfaces
	void notify_upcalls(const DGService_DGBasicLink::DGBasicLinkObject &input);
	
protected:
	virtual void handle_input(const DGService_DGBasicLink::DGBasicLinkObject &input) {
		// relay input-handling to all attached GrayImage1UpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	GrayImage1UpcallManager(
		Smart::InputSubject<DGService_DGBasicLink::DGBasicLinkObject> *subject,
		const int &prescaleFactor=1
	);
	virtual ~GrayImage1UpcallManager();
	
	void attach(GrayImage1UpcallInterface *upcall);
	void detach(GrayImage1UpcallInterface *upcall);
};

#endif
