//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _GRAYIMAGECOLLECTOR_CORE_HH
#define _GRAYIMAGECOLLECTOR_CORE_HH
	
#include "aceSmartSoft.hh"

// include upcall interface
#include "GrayImage1UpcallInterface.hh"
#include "GrayImage2UpcallInterface.hh"

// include communication-objects for output ports

// include all interaction-observer interfaces
#include <GrayImageCollectorObserverInterface.hh>


class GrayImageCollectorCore
:	public SmartACE::ManagedTask
,	public Smart::TaskTriggerSubject
,	public GrayImage1UpcallInterface
,	public GrayImage2UpcallInterface
{
private:
	bool useDefaultState; 
	bool useLogging;
	int taskLoggingId;
	unsigned int currentUpdateCount;
	
	Smart::StatusCode grayImage1Status;
	DomainVision::CommVideoImage grayImage1Object;
	Smart::StatusCode grayImage2Status;
	DomainVision::CommVideoImage grayImage2Object;
	
	
protected:
	virtual int execute_protected_region();
	
	virtual void updateAllCommObjects();
	
	virtual int getPreviousCommObjId();
	
	void triggerLogEntry(const int& idOffset);
	
	
	// overload and implement this method in derived classes to immediately get all incoming updates from GrayImage1 (as soon as they arrive)
	virtual void on_GrayImage1(const DomainVision::CommVideoImage &input) {
		// no-op
	}
	
	// this method can be safely used from the thread in derived classes
	inline Smart::StatusCode grayImage1GetUpdate(DomainVision::CommVideoImage &grayImage1Object) const
	{
		// copy local object buffer and return the last status code
		grayImage1Object = this->grayImage1Object;
		return grayImage1Status;
	}
	// overload and implement this method in derived classes to immediately get all incoming updates from GrayImage2 (as soon as they arrive)
	virtual void on_GrayImage2(const DomainVision::CommVideoImage &input) {
		// no-op
	}
	
	// this method can be safely used from the thread in derived classes
	inline Smart::StatusCode grayImage2GetUpdate(DomainVision::CommVideoImage &grayImage2Object) const
	{
		// copy local object buffer and return the last status code
		grayImage2Object = this->grayImage2Object;
		return grayImage2Status;
	}
	
	
	
/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<GrayImageCollectorObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(GrayImageCollectorObserverInterface *observer);
	void detach_interaction_observer(GrayImageCollectorObserverInterface *observer);

public:
	GrayImageCollectorCore(Smart::IComponent *comp, const bool &useDefaultState=true);
	virtual ~GrayImageCollectorCore();
	
	inline void setUpLogging(const int &taskNbr, const bool &useLogging=true) {
		this->taskLoggingId = taskNbr;
		this->useLogging = useLogging;
	}
	
	inline bool isLoggingActive() const {
		return useLogging;
	}
	
	inline int getLoggingID() const {
		return taskLoggingId;
	}
	
	inline int getCurrentUpdateCount() const {
		return currentUpdateCount;
	}
	
};
#endif
