//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "GrayImageCollectorCore.hh"
#include "GrayImageCollector.hh"
#include "TwoMapMaker.hh"

//FIXME: use logging
//#include "smartGlobalLogger.hh"

// include observers


GrayImageCollectorCore::GrayImageCollectorCore(Smart::IComponent *comp, const bool &useDefaultState) 
:	SmartACE::ManagedTask(comp)
,	useDefaultState(useDefaultState)
,	useLogging(false)
,	taskLoggingId(0)
,	currentUpdateCount(0)
,	grayImage1Status(Smart::SMART_DISCONNECTED)
,	grayImage1Object()
,	grayImage2Status(Smart::SMART_DISCONNECTED)
,	grayImage2Object()
{
}

GrayImageCollectorCore::~GrayImageCollectorCore()
{
}


void GrayImageCollectorCore::notify_all_interaction_observers() {
	std::unique_lock<std::mutex> lock(interaction_observers_mutex);
	// try dynamically down-casting this class to the derived class 
	// (we can do it safely here as we exactly know the derived class)
	if(const GrayImageCollector* grayImageCollector = dynamic_cast<const GrayImageCollector*>(this)) {
		for(auto it=interaction_observers.begin(); it!=interaction_observers.end(); it++) {
			(*it)->on_update_from(grayImageCollector);
		}
	}
}

void GrayImageCollectorCore::attach_interaction_observer(GrayImageCollectorObserverInterface *observer) {
	std::unique_lock<std::mutex> lock(interaction_observers_mutex);
	interaction_observers.push_back(observer);
}

void GrayImageCollectorCore::detach_interaction_observer(GrayImageCollectorObserverInterface *observer) {
	std::unique_lock<std::mutex> lock(interaction_observers_mutex);
	interaction_observers.remove(observer);
}

int GrayImageCollectorCore::execute_protected_region()
{
	
	// update of comm-objects must be within the protected region to prevent aged comm-object values
	this->updateAllCommObjects();
	
	if(useLogging == true) {
		//FIXME: use logging
		//Smart::LOGGER->log(taskLoggingId, getCurrentUpdateCount(), getPreviousCommObjId());
	}
	
	// this is the user code (should not internally use the state-pattern any more)
	int retval = this->on_execute();
	
	// notify all attached interaction observers
	this->notify_all_interaction_observers();
	
	// inform all associated tasks about a new update
	this->trigger_all_tasks();
	
	// increment current currentUpdateCount for the next iteration
	currentUpdateCount++;
	
	return retval;
}


void GrayImageCollectorCore::updateAllCommObjects()
{
	grayImage1Status = COMP->grayImage1InputTaskTrigger->getUpdate(grayImage1Object);
	grayImage2Status = COMP->grayImage2InputTaskTrigger->getUpdate(grayImage2Object);
	
}



void GrayImageCollectorCore::triggerLogEntry(const int& idOffset)
{
	if(useLogging == true) {
		int logId = taskLoggingId + 2*2 + idOffset;
		//FIXME: use logging
		//Smart::LOGGER->log(logId, getCurrentUpdateCount(), getPreviousCommObjId());
	}
}

int GrayImageCollectorCore::getPreviousCommObjId()
{
	// this method needs to be overloaded and implemented in derived classes
	return 0;
}
