//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "Image1UpcallManager.hh"

Image1UpcallManager::Image1UpcallManager(
	Smart::InputSubject<DGService_DGBasicLink::DGBasicLinkObject> *subject,
	const int &prescaleFactor)
	:	Smart::IInputHandler<DGService_DGBasicLink::DGBasicLinkObject>(subject, prescaleFactor)
{  }
Image1UpcallManager::~Image1UpcallManager()
{  }

void Image1UpcallManager::notify_upcalls(const DGService_DGBasicLink::DGBasicLinkObject &input)
{
	for(auto it=upcalls.begin(); it!=upcalls.end(); it++) {
		(*it)->on_Image1(input);
	}
}

void Image1UpcallManager::attach(Image1UpcallInterface *upcall)
{
	upcalls.push_back(upcall);
}
void Image1UpcallManager::detach(Image1UpcallInterface *upcall)
{
	upcalls.remove(upcall);
}
