//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef TWOMAPMAKER_PORTFACTORYINTERFACE_HH_
#define TWOMAPMAKER_PORTFACTORYINTERFACE_HH_

// include communication objects
#include <DGService_DGBasicLink/DGBasicLinkObject.hh>
#include <DGService_DGBasicLink/DGBasicLinkObjectACE.hh>

#include <chrono>

// include component's main class
#include "TwoMapMaker.hh"

// forward declaration
class TwoMapMaker;

class TwoMapMakerPortFactoryInterface {
public:
	TwoMapMakerPortFactoryInterface() { };
	virtual ~TwoMapMakerPortFactoryInterface() { };

	virtual void initialize(TwoMapMaker *component, int argc, char* argv[]) = 0;
	virtual int onStartup() = 0;

	virtual Smart::IPushClientPattern<DGService_DGBasicLink::DGBasicLinkObject> * createGrayImage1() = 0;
	virtual Smart::IPushClientPattern<DGService_DGBasicLink::DGBasicLinkObject> * createGrayImage2() = 0;
	virtual Smart::IPushClientPattern<DGService_DGBasicLink::DGBasicLinkObject> * createImage1() = 0;
	virtual Smart::IPushClientPattern<DGService_DGBasicLink::DGBasicLinkObject> * createImage2() = 0;
	
	virtual Smart::IPushServerPattern<DGService_DGBasicLink::DGBasicLinkObject> * createGrayMap(const std::string &serviceName) = 0;
	virtual Smart::IPushServerPattern<DGService_DGBasicLink::DGBasicLinkObject> * createRGBMap(const std::string &serviceName) = 0;

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) = 0;
	virtual void destroy() = 0;
};

#endif /* TWOMAPMAKER_PORTFACTORYINTERFACE_HH_ */
