//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ZeroCamera.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ZeroCameraAcePortFactory.hh"


// initialize static singleton pointer to zero
ZeroCamera* ZeroCamera::_zeroCamera = 0;

// constructor
ZeroCamera::ZeroCamera()
{
	std::cout << "constructor of ZeroCamera\n";
	
	// set all pointer members to NULL
	grayImage = NULL;
	imageCapture = NULL;
	imageCaptureTrigger = NULL;
	rGBImage = NULL;
	rgb2gray = NULL;
	rgb2grayTrigger = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "ZeroCamera";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.grayImage.serviceName = "GrayImage";
	connections.grayImage.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBImage.serviceName = "RGBImage";
	connections.rGBImage.roboticMiddleware = "ACE_SmartSoft";
	connections.imageCapture.minActFreq = 0.0;
	connections.imageCapture.maxActFreq = 0.0;
	// scheduling default parameters
	connections.imageCapture.scheduler = "DEFAULT";
	connections.imageCapture.priority = -1;
	connections.imageCapture.cpuAffinity = -1;
	connections.rgb2gray.minActFreq = 0.0;
	connections.rgb2gray.maxActFreq = 0.0;
	// scheduling default parameters
	connections.rgb2gray.scheduler = "DEFAULT";
	connections.rgb2gray.priority = -1;
	connections.rgb2gray.cpuAffinity = -1;
	
	// initialize members of PlainOpcUaZeroCameraExtension
	
}

void ZeroCamera::addPortFactory(const std::string &name, ZeroCameraPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ZeroCamera::addExtension(ZeroCameraExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ZeroCamera::getComponentImpl()
{
	return dynamic_cast<ZeroCameraAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ZeroCamera::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}




/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ZeroCamera::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ZeroCamera::startAllTasks() {
	// start task ImageCapture
	if(connections.imageCapture.scheduler != "DEFAULT") {
		ACE_Sched_Params imageCapture_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.imageCapture.scheduler == "FIFO") {
			imageCapture_SchedParams.policy(ACE_SCHED_FIFO);
			imageCapture_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.imageCapture.scheduler == "RR") {
			imageCapture_SchedParams.policy(ACE_SCHED_RR);
			imageCapture_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		imageCapture->start(imageCapture_SchedParams, connections.imageCapture.cpuAffinity);
	} else {
		imageCapture->start();
	}
	// start task rgb2gray
	if(connections.rgb2gray.scheduler != "DEFAULT") {
		ACE_Sched_Params rgb2gray_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.rgb2gray.scheduler == "FIFO") {
			rgb2gray_SchedParams.policy(ACE_SCHED_FIFO);
			rgb2gray_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.rgb2gray.scheduler == "RR") {
			rgb2gray_SchedParams.policy(ACE_SCHED_RR);
			rgb2gray_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		rgb2gray->start(rgb2gray_SchedParams, connections.rgb2gray.cpuAffinity);
	} else {
		rgb2gray->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ZeroCamera::startAllTimers() {
}


Smart::TaskTriggerSubject* ZeroCamera::getInputTaskTriggerFromString(const std::string &client)
{
	
	return NULL;
}


void ZeroCamera::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of PlainOpcUaZeroCameraExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ZeroCameraPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ZeroCameraAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ZeroCamera is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		grayImage = portFactoryRegistry[connections.grayImage.roboticMiddleware]->createGrayImage(connections.grayImage.serviceName);
		rGBImage = portFactoryRegistry[connections.rGBImage.roboticMiddleware]->createRGBImage(connections.rGBImage.serviceName);
		
		// create client ports
		
		// create InputTaskTriggers and UpcallManagers
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		
		
		
		// create Task ImageCapture
		imageCapture = new ImageCapture(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.imageCapture.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.imageCapture.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(imageCapture);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				imageCaptureTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task ImageCapture" << std::endl;
			}
		} else if(connections.imageCapture.trigger == "DataTriggered") {
			imageCaptureTrigger = getInputTaskTriggerFromString(connections.imageCapture.inPortRef);
			if(imageCaptureTrigger != NULL) {
				imageCaptureTrigger->attach(imageCapture, connections.imageCapture.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.imageCapture.inPortRef << " as activation source for Task ImageCapture" << std::endl;
			}
		} 
		
		// create Task rgb2gray
		rgb2gray = new Rgb2gray(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.rgb2gray.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.rgb2gray.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(rgb2gray);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				rgb2grayTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task Rgb2gray" << std::endl;
			}
		} else if(connections.rgb2gray.trigger == "DataTriggered") {
			rgb2grayTrigger = getInputTaskTriggerFromString(connections.rgb2gray.inPortRef);
			if(rgb2grayTrigger != NULL) {
				rgb2grayTrigger->attach(rgb2gray, connections.rgb2gray.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.rgb2gray.inPortRef << " as activation source for Task Rgb2gray" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ZeroCamera::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ZeroCamera::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(imageCaptureTrigger != NULL){
		imageCaptureTrigger->detach(imageCapture);
		delete imageCapture;
	}
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(rgb2grayTrigger != NULL){
		rgb2grayTrigger->detach(rgb2gray);
		delete rgb2gray;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers

	// destroy client ports

	// destroy server ports
	delete grayImage;
	delete rGBImage;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of PlainOpcUaZeroCameraExtension
	
}

void ZeroCamera::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ZeroCamera.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ZeroCamera.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ZeroCamera.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		
		// load parameters for server GrayImage
		parameter.getString("GrayImage", "serviceName", connections.grayImage.serviceName);
		if(parameter.checkIfParameterExists("GrayImage", "roboticMiddleware")) {
			parameter.getString("GrayImage", "roboticMiddleware", connections.grayImage.roboticMiddleware);
		}
		// load parameters for server RGBImage
		parameter.getString("RGBImage", "serviceName", connections.rGBImage.serviceName);
		if(parameter.checkIfParameterExists("RGBImage", "roboticMiddleware")) {
			parameter.getString("RGBImage", "roboticMiddleware", connections.rGBImage.roboticMiddleware);
		}
		
		// load parameters for task ImageCapture
		parameter.getDouble("ImageCapture", "minActFreqHz", connections.imageCapture.minActFreq);
		parameter.getDouble("ImageCapture", "maxActFreqHz", connections.imageCapture.maxActFreq);
		parameter.getString("ImageCapture", "triggerType", connections.imageCapture.trigger);
		if(connections.imageCapture.trigger == "PeriodicTimer") {
			parameter.getDouble("ImageCapture", "periodicActFreqHz", connections.imageCapture.periodicActFreq);
		} else if(connections.imageCapture.trigger == "DataTriggered") {
			parameter.getString("ImageCapture", "inPortRef", connections.imageCapture.inPortRef);
			parameter.getInteger("ImageCapture", "prescale", connections.imageCapture.prescale);
		}
		if(parameter.checkIfParameterExists("ImageCapture", "scheduler")) {
			parameter.getString("ImageCapture", "scheduler", connections.imageCapture.scheduler);
		}
		if(parameter.checkIfParameterExists("ImageCapture", "priority")) {
			parameter.getInteger("ImageCapture", "priority", connections.imageCapture.priority);
		}
		if(parameter.checkIfParameterExists("ImageCapture", "cpuAffinity")) {
			parameter.getInteger("ImageCapture", "cpuAffinity", connections.imageCapture.cpuAffinity);
		}
		// load parameters for task rgb2gray
		parameter.getDouble("rgb2gray", "minActFreqHz", connections.rgb2gray.minActFreq);
		parameter.getDouble("rgb2gray", "maxActFreqHz", connections.rgb2gray.maxActFreq);
		parameter.getString("rgb2gray", "triggerType", connections.rgb2gray.trigger);
		if(connections.rgb2gray.trigger == "PeriodicTimer") {
			parameter.getDouble("rgb2gray", "periodicActFreqHz", connections.rgb2gray.periodicActFreq);
		} else if(connections.rgb2gray.trigger == "DataTriggered") {
			parameter.getString("rgb2gray", "inPortRef", connections.rgb2gray.inPortRef);
			parameter.getInteger("rgb2gray", "prescale", connections.rgb2gray.prescale);
		}
		if(parameter.checkIfParameterExists("rgb2gray", "scheduler")) {
			parameter.getString("rgb2gray", "scheduler", connections.rgb2gray.scheduler);
		}
		if(parameter.checkIfParameterExists("rgb2gray", "priority")) {
			parameter.getInteger("rgb2gray", "priority", connections.rgb2gray.priority);
		}
		if(parameter.checkIfParameterExists("rgb2gray", "cpuAffinity")) {
			parameter.getInteger("rgb2gray", "cpuAffinity", connections.rgb2gray.cpuAffinity);
		}
		
		// load parameters for PlainOpcUaZeroCameraExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
