//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef ZEROCAMERA_ACE_PORTFACTORY_HH_
#define ZEROCAMERA_ACE_PORTFACTORY_HH_

// include ACE/SmartSoft component implementation
#include "ZeroCameraImpl.hh"

// include the main component-definition class
#include "ZeroCameraPortFactoryInterface.hh"

class ZeroCameraAcePortFactory: public ZeroCameraPortFactoryInterface
{
private:
	ZeroCameraImpl *componentImpl;
public:
	ZeroCameraAcePortFactory();
	virtual ~ZeroCameraAcePortFactory();

	virtual void initialize(ZeroCamera *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	
	virtual Smart::IPushServerPattern<DGService_DGBasicLink::DGBasicLinkObject> * createGrayImage(const std::string &serviceName) override;
	virtual Smart::IPushServerPattern<DGService_DGBasicLink::DGBasicLinkObject> * createRGBImage(const std::string &serviceName) override;
	
	// get a pointer to the internal component implementation
	SmartACE::SmartComponent* getComponentImpl();

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* ZEROCAMERA_ACE_PORTFACTORY_HH_ */
