//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _ZEROCAMERA_HH
#define _ZEROCAMERA_HH

#include <map>
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "ZeroCameraCore.hh"

#include "ZeroCameraPortFactoryInterface.hh"
#include "ZeroCameraExtension.hh"

// forward declarations
class ZeroCameraPortFactoryInterface;
class ZeroCameraExtension;

// includes for PlainOpcUaZeroCameraExtension
// include plain OPC UA device clients
// include plain OPC UA status servers


// include communication objects
#include <DomainVision/CommVideoImage.hh>
#include <DomainVision/CommVideoImageACE.hh>

// include tasks
#include "ImageCapture.hh"
#include "Rgb2gray.hh"
// include UpcallManagers

// include input-handler(s)
// include request-handler(s)

// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP ZeroCamera::instance()

class ZeroCamera : public ZeroCameraCore {
private:
	static ZeroCamera *_zeroCamera;
	
	// constructor
	ZeroCamera();
	
	// copy-constructor
	ZeroCamera(const ZeroCamera& cc);
	
	// destructor
	~ZeroCamera() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	// helper method that maps a string-name to an according TaskTriggerSubject
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
	// internal map storing the different port-creation factories (that internally map to specific middleware implementations)
	std::map<std::string, ZeroCameraPortFactoryInterface*> portFactoryRegistry;
	
	// internal map storing various extensions of this component class
	std::map<std::string, ZeroCameraExtension*> componentExtensionRegistry;
	
public:
	
	// define tasks
	Smart::TaskTriggerSubject* imageCaptureTrigger;
	ImageCapture *imageCapture;
	Smart::TaskTriggerSubject* rgb2grayTrigger;
	Rgb2gray *rgb2gray;
	
	// define input-ports
	
	// define request-ports
	
	// define input-handler
	
	// define output-ports
	Smart::IPushServerPattern<DomainVision::CommVideoImage> *grayImage;
	Smart::IPushServerPattern<DomainVision::CommVideoImage> *rGBImage;
	
	// define answer-ports
	
	// define request-handlers
	
	// definitions of PlainOpcUaZeroCameraExtension
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	/// this method is used to register different PortFactory classes (one for each supported middleware framework)
	void addPortFactory(const std::string &name, ZeroCameraPortFactoryInterface *portFactory);
	
	SmartACE::SmartComponent* getComponentImpl();
	
	/// this method is used to register different component-extension classes
	void addExtension(ZeroCameraExtension *extension);
	
	/// this method allows to access the registered component-extensions (automatically converting to the actuall implementation type)
	template <typename T>
	T* getExtension(const std::string &name) {
		auto it = componentExtensionRegistry.find(name);
		if(it != componentExtensionRegistry.end()) {
			return dynamic_cast<T*>(it->second);
		}
		return 0;
	}
	
	/// initialize component's internal members
	void init(int argc, char *argv[]);
	
	/// execute the component's infrastructure
	void run();
	
	/// clean-up component's resources
	void fini();
	
	/// call this method to set the overall component into the Alive state (i.e. component is then ready to operate)
	void setStartupFinished();
	
	/// connect all component's client ports
	Smart::StatusCode connectAndStartAllServices();
	
	/// start all assocuated Activities
	void startAllTasks();
	
	/// start all associated timers
	void startAllTimers();
	

	// return singleton instance
	static ZeroCamera* instance()
	{
		if(_zeroCamera == 0) {
			_zeroCamera = new ZeroCamera();
		}
		return _zeroCamera;
	}
	
	static void deleteInstance() {
		if(_zeroCamera != 0) {
			delete _zeroCamera;
		}
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct ImageCapture_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} imageCapture;
		struct Rgb2gray_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} rgb2gray;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct GrayImage_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} grayImage;
		struct RGBImage_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} rGBImage;
	
		//--- client port parameter ---
		
		// -- parameters for PlainOpcUaZeroCameraExtension
		
	} connections;
};
#endif
