//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _GRAYIMAGECOLLECTOR_HH
#define _GRAYIMAGECOLLECTOR_HH

#include "GrayImageCollectorCore.hh"

class GrayImageCollector  : public GrayImageCollectorCore
{
private:
	virtual void on_GrayImage1(const DGService_DGBasicLink::DGBasicLinkObject &input);
	virtual void on_GrayImage2(const DGService_DGBasicLink::DGBasicLinkObject &input);
public:
	GrayImageCollector(SmartACE::SmartComponent *comp);
	virtual ~GrayImageCollector();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
