//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "ImageCollector.hh"
#include "TwoMapMaker.hh"

#include <iostream>

ImageCollector::ImageCollector(SmartACE::SmartComponent *comp) 
:	ImageCollectorCore(comp)
{
	std::cout << "constructor ImageCollector\n";
}
ImageCollector::~ImageCollector() 
{
	std::cout << "destructor ImageCollector\n";
}


void ImageCollector::on_Image1(const DGService_DGBasicLink::DGBasicLinkObject &input)
{
	// upcall triggered from InputPort Image1
	// - use a local mutex here, because this upcal is called asynchroneously from outside of this task
	// - do not use longer blocking calls here since this upcall blocks the InputPort Image1
	// - if you need to implement a long-running procedure, do so within the on_execute() method and in
	//   there, use the method image1GetUpdate(input) to get a copy of the input object
}
void ImageCollector::on_Image2(const DGService_DGBasicLink::DGBasicLinkObject &input)
{
	// upcall triggered from InputPort Image2
	// - use a local mutex here, because this upcal is called asynchroneously from outside of this task
	// - do not use longer blocking calls here since this upcall blocks the InputPort Image2
	// - if you need to implement a long-running procedure, do so within the on_execute() method and in
	//   there, use the method image2GetUpdate(input) to get a copy of the input object
}
int ImageCollector::on_entry()
{
	// do initialization procedures here, which are called once, each time the task is started
	// it is possible to return != 0 (e.g. when initialization fails) then the task is not executed further
	return 0;
}
int ImageCollector::on_execute()
{
	// this method is called from an outside loop,
	// hence, NEVER use an infinite loop (like "while(1)") here inside!!!
	// also do not use blocking calls which do not result from smartsoft kernel
	
	// to get the incoming data, use this methods:
	Smart::StatusCode status;
	DGService_DGBasicLink::DGBasicLinkObject image1Object;
	status = this->image1GetUpdate(image1Object);
	if(status != Smart::SMART_OK) {
		std::cerr << status << std::endl;
		// return 0;
	} else {
		std::cout << "received: " << image1Object << std::endl;
	}
	DGService_DGBasicLink::DGBasicLinkObject image2Object;
	status = this->image2GetUpdate(image2Object);
	if(status != Smart::SMART_OK) {
		std::cerr << status << std::endl;
		// return 0;
	} else {
		std::cout << "received: " << image2Object << std::endl;
	}

	std::cout << "Hello from ImageCollector " << std::endl;

	// it is possible to return != 0 (e.g. when the task detects errors), then the outer loop breaks and the task stops
	return 0;
}
int ImageCollector::on_exit()
{
	// use this method to clean-up resources which are initialized in on_entry() and needs to be freed before the on_execute() can be called again
	return 0;
}
