//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DGSERVICE_DGBASICLINK_DGBASICLINKOBJECT_ACE_H_
#define DGSERVICE_DGBASICLINK_DGBASICLINKOBJECT_ACE_H_

#include "DGService_DGBasicLink/DGBasicLinkObject.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure DGBasicLinkObject
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DGService_DGBasicLinkIDL::DGBasicLinkObject &data);

// de-serialization operator for DataStructure DGBasicLinkObject
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DGService_DGBasicLinkIDL::DGBasicLinkObject &data);

// serialization operator for CommunicationObject DGBasicLinkObject
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DGService_DGBasicLink::DGBasicLinkObject &obj);

// de-serialization operator for CommunicationObject DGBasicLinkObject
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DGService_DGBasicLink::DGBasicLinkObject &obj);

#endif /* DGSERVICE_DGBASICLINK_DGBASICLINKOBJECT_ACE_H_ */
