//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DGSERVICE_DGBASICLINK_DGBASICLINKOBJECT_CORE_H_
#define DGSERVICE_DGBASICLINK_DGBASICLINKOBJECT_CORE_H_

#include "DGService_DGBasicLink/DGBasicLinkObjectData.hh"

#include <iostream>
#include <string>
#include <list>

namespace DGService_DGBasicLink {
	
class DGBasicLinkObjectCore {
protected:
	// data structure
	DGService_DGBasicLinkIDL::DGBasicLinkObject idl_DGBasicLinkObject;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DGService_DGBasicLinkIDL::DGBasicLinkObject DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	DGBasicLinkObjectCore();
	DGBasicLinkObjectCore(const DATATYPE &data);
	// default destructor
	virtual ~DGBasicLinkObjectCore();
	
	const DATATYPE& get() const { return idl_DGBasicLinkObject; }
	operator const DATATYPE&() const { return idl_DGBasicLinkObject; }
	DATATYPE& set() { return idl_DGBasicLinkObject; }

	static inline std::string identifier(void) { return "DGService_DGBasicLink::DGBasicLinkObject"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Name
	inline std::string getName() const { return idl_DGBasicLinkObject.name; }
	inline DGBasicLinkObjectCore& setName(const std::string &name) { idl_DGBasicLinkObject.name = name; return *this; }
};

} /* namespace DGService_DGBasicLink */
#endif /* DGSERVICE_DGBASICLINK_DGBASICLINKOBJECT_CORE_H_ */
