//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _IMAGEVIEWER_HH
#define _IMAGEVIEWER_HH

#include "ImageViewerCore.hh"

class ImageViewer  : public ImageViewerCore
{
private:
public:
	ImageViewer(SmartACE::SmartComponent *comp);
	virtual ~ImageViewer();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
